### ISSUE TITLE
What happened to /u/vredditshare

### ISSUE THREAD

**Issue by AggelosM** [pmdevita/vredditshare#6]
It says page not found.

EDIT: This works great, thank you pmdevita!
https://vreddit.cc/

**Comment by pmdevita** [comment]
https://www.reddit.com/r/vredditshare/comments/eq220j/vredditshare_has_been_shadowbanned/

**Comment by pmdevita** [comment]
Reopening so it is visible on the issues page to other people who may come by here

**Comment by pmdevita** [comment]
The issue has been resolved, closing.
